# Site
repository: psi9730/resume
# favicon: images/favicon.ico
# Personal info
name: Seungil Park
title: Sophomore web programmer
email: psi9730@naver.com
website: https://psi9730.github.io/machinelearning-blog/

# Social links
github_username:  psi9730


# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs

  I am most skilled in: <mark>tensorflow</mark>, <mark>pytorch</mark>, <mark>docker</mark>, <mark>react.js</mark>, <mark>vue.js</mark>, <mark>angular.js</mark>, <mark>jquery</mark>, <mark>mysql</mark>, <mark>react-native</mark>, <mark>php</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  웹 프로그래밍, 머신러닝 공부 이외의 나의 관심사:
   - 운동(웨이트 트레이닝, 필라테스)
   - 맛있는 음식 먹기

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
