# Site
repository: psi9730/resume
# favicon: images/favicon.ico
# Personal info
name: Seungil Park
title: web programmer
email: psi9730@gmail.com
website: psi9730.github.io/resume/

# Social links
github_username: psi9730

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am most skilled in: <mark>react.js</mark>, <mark>typescript</mark>, <mark>redux-saga</mark>, <mark>story-book</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
